# Generated by Django 2.2.7 on 2021-06-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contus', '0002_auto_20210628_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(),
        ),
    ]
